board: 6 Pack
name: Koalamodule_CNC
stepping:
  engine: RMT
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 0
  disable_delay_us: 0
  segments: 12
kinematics: {}
axes:
  homing_runs: 2
  x:
    steps_per_mm: 400
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 1000
    max_travel_mm: 195
    soft_limits: false
    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.13:pu:low
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 5
      standard_stepper:
        step_pin: gpio.26
        direction_pin: gpio.16
        disable_pin: NO_PIN
    homing:
      cycle: 2
      mpos_mm: 195
      positive_direction: true
      seek_mm_per_min: 1000
      seek_scaler: 1.5
  y:
    steps_per_mm: 400
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 1000
    max_travel_mm: 195
    soft_limits: false
    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.5:pu:low
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 5
      standard_stepper:
        step_pin: gpio.25
        direction_pin: gpio.27
        disable_pin: NO_PIN
    homing:
      cycle: 2
      mpos_mm: 195
      seek_mm_per_min: 1000
      positive_direction: true
      seek_scaler: 1.5
  z:
    steps_per_mm: 400
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 1000
    max_travel_mm: 150
    soft_limits: false
    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: gpio.23:pu:low
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 5
      standard_stepper:
        step_pin: gpio.17
        direction_pin: gpio.14
        disable_pin: NO_PIN
    homing:
      cycle: 2
      mpos_mm: 195
      seek_mm_per_min: 1000
      positive_direction: true
      seek_scaler: 1.5
  shared_stepper_disable_pin: gpio.12
  shared_stepper_reset_pin: NO_PIN
coolant:
  flood_pin: NO_PIN
  mist_pin: NO_PIN
  delay_ms: 0
macros: {}
start:
  must_home: false
  deactivate_parking: false
  check_limits: false
parking:
  enable: false
  axis: Z
  target_mpos_mm: -5
  rate_mm_per_min: 800
  pullout_distance_mm: 5
  pullout_rate_mm_per_min: 250
user_outputs:
  analog0_pin: NO_PIN
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  analog0_hz: 5000
  analog1_hz: 5000
  analog2_hz: 5000
  analog3_hz: 5000
  digital0_pin: NO_PIN
  digital1_pin: NO_PIN
  digital2_pin: NO_PIN
  digital3_pin: NO_PIN
  digital4_pin: NO_PIN
  digital5_pin: NO_PIN
  digital6_pin: NO_PIN
  digital7_pin: NO_PIN
user_inputs:
  analog0_pin: NO_PIN
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  digital0_pin: NO_PIN
  digital1_pin: NO_PIN
  digital2_pin: NO_PIN
  digital3_pin: NO_PIN
  digital4_pin: NO_PIN
  digital5_pin: NO_PIN
  digital6_pin: NO_PIN
  digital7_pin: NO_PIN
arc_tolerance_mm: 0.002
junction_deviation_mm: 0.01
verbose_errors: true
report_inches: false
enable_parking_override_control: false
use_line_numbers: false
planner_blocks: 16
